version: "3"
services:
  db:
    image: postgres
    container_name: se-db
    tty: true
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "seapp"
    volumes:
      - postgres_se:/var/lib/postgresql/data
    restart: always
    networks:
      default:
        ipv4_address: 198.165.1.2
    ports:
      - "5432:5432"
  redis:
    image: redis
    restart: always
    container_name: se-redis
    networks:
      default:
        ipv4_address: 198.165.1.3
    ports:
      - "6379:6379"
  memcached-1:
    image: memcached
    restart: always
    container_name: memcached-se-1
    networks:
      default:
        ipv4_address: 198.165.1.11
    ports:
      - "11211:11211"
  api:
    depends_on:
      - db
      - redis
      - memcached-1
    build:
      args:
        user: sl
        uid: 1000
        pass: sl
      context: ./docker
      dockerfile: Dockerfile
    image: se
    container_name: se-admin
    entrypoint: /docker-entrypoint.sh
    restart: always
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
    networks:
      default:
        ipv4_address: 198.165.1.5
  nginx:
    image: nginx:alpine
    container_name: se-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/ssl/:/etc/nginx/ssl/
    networks:
      default:
        ipv4_address: 198.165.1.6
networks:
  default:
    ipam:
      config:
        - subnet: 198.165.1.0/24
volumes:
  postgres_se:
    driver: local
